#!/bin/bash

######################################################################
# ssl-killer
# search and copy Exploit from exploit-db 2 metasploit-framework
# Needs searchsploit amd metasploit-framework installed
# script install this tools for you
# First run from github directory ./ssl-killer ... after install
# use command ssl-killer system wide
# command: > ssl-killer $searchsting1 $searchstring2 $searchstring3
######################################################################

######################################################################
# create 16.09.2017
# last modify: 21.09.2017
# bug or anything: d43M0n23@3xpl0it.com
######################################################################

######################################################################

# Bash sTyl3!
clear='\033[0m'			#alle Attribute zurücksetzen
red='\e[31m'			#Schriftfarbe rot
bold='\033[1m'			#Fettschrift
underline='\033[4m'		#Unterstreichen
blinken='\033[5m'		#Blinken
invers='\033[7m'		#inverse Darstellung
black='\033[30m'		#Schriftfarbe schwarz
red='\033[31m'			#Schriftfarbe rot
green='\033[32m'		#Schriftfarbe grün
yell='\033[33m'			#Schriftfarbe gelb
blue='\033[34m'			#Schriftfarbe blau
mag='\033[35m'			#Schriftfarbe magenta
turk='\033[36m'			#Schriftfarbe türkis
white='\033[37m'		#Schriftfarbe weiß
orange='\033[93m'		#Schriftfarbe orange
######################################################################


##Variablen
DATE=$(date +%F)
version=v1.0
vdate=16.09.2017

# Local Destination
INSTALL_DIR=/usr/share/ssl-killer

# Exploit-db dir
SOURCE_PATH=/usr/share/exploitdb/platforms

# MSF4 - Metasploit user dir
MSF_PATH=$HOME/.msf4/modules/exploits


# Tools install
if ! hash searchsploit 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes searchsploit ; fi
if ! hash msfconsole 2>/dev/null; then sudo apt-get update && apt-get upgrade -y; sudo apt-get install --yes metasploit-framework ; fi

#INSTALL
if [ ! -d $INSTALL_DIR ]; then
echo -e "\n${green} + -- --=[This is your first run of the ssl-killer script${clear}"
echo -e "${green} + -- --=[This script will install ssl-killer under $INSTALL_DIR.${clear}"
echo -e "${green} + -- --=[After install you can use the command 'ssl-killer' Server/System wide and remove the downloaded git folder${clear}"
sleep 2
mkdir -p $INSTALL_DIR 2> /dev/null
cp -Rf $PWD/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/copysploit
rm -f /usr/bin/ssl-killer
ln -s $INSTALL_DIR/ssl-killer /usr/bin/ssl-killer
echo -e "${green} + -- --=[Installation Finish.${clear}"
sleep 2
fi

### FUNCTIONS ###
#Latest release
LATEST_RELEASE=$(curl -L -s -H 'Accept: application/json' https://github.com/d43M0n23/ssl-killer/releases/latest)
LATEST_VERSION=$(echo $LATEST_RELEASE | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')

#UPDATE NEW VERSION
if [ "$LATEST_VERSION" != "$version" ]; then
echo -e "\n${red}Your Version of ssl-killer is outdated!${clear}"
echo -e "\n${green}Please use the update function: ssl-killer --update!${clear}"
sleep 5
fi

#UPDATE
if [ "$1"  = "--update" ]; then
echo -e "\n${turk}You have select the update Feature${clear}"
sleep 2
cd /tmp/
git clone https://github.com/d43M0n23/ssl-killer.git
cp -Rf ssl-killer/* $INSTALL_DIR 2> /dev/null
rm -f /usr/bin/ssl-killer
ln -s $INSTALL_DIR/ssl-killer /usr/bin/ssl-killer
echo -e "\n${green}Update finish.Please restart ssl-killer.${clear}"
rm -r ssl-killer
exit
fi

#UNINSTALL
if [ "$1"  = "--deinstall" ]; then
echo -e "\n${turk}You have select the deinstall Feature${clear}"
sleep 2
rm -f /usr/bin/ssl-killer
cd /usr/share/
rm -r ssl-killer/
echo -e "\n${turk}deinstall Finish${clear}"
cd
exit
fi

#START MAINSTAGE
clear
echo -e '\n'
echo -e '             __    __    _ ____       '
echo -e '    ___ ___ / /___/ /__ (_) / /__ ____'
echo -e '   (_-<(_-</ /___/  '_// / / / -_) __/'
echo -e '  /___/___/_/   /_/\_\/_/_/_/\__/_/   '

echo -e "\n${orange} + -- --=[https://3xpl0it.com${clear} ${red}Version ${version}${clear}"
sleep 1


echo -e "\n"
cat <<EOF
Enter Your Target.
EOF
